#server:
#  port: 7788 #服务端口
#spring:
#  application:
#    name: microservice-config-server #指定服务名
#  cloud:
#    config:
#      server:
#        git: #配置git仓库地址
#          uri: https://github.com/hyyms/APIStore.Microservices.git
#          search-paths:
#            - SpringCloud
#          username: huiyiyunmishu@163.com
#          password: 2018hyyms_GitHub
#      label: master #分支名称



server:
  port: 7788 #服务端口
spring:
  application:
    name:  microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/hyyms/APIStore.Microservices.git
          search-paths:
            - myspringcloudconfig		#配置文件目录地址
          username: huiyiyunmishu@163.com	#码云账号（公有项目不需要设置）
          password: 2018hyyms_GitHub 	#码云密码（公有项目不需要设置）
      label: master	#分支名称