server:
  port: 7788 #服务端口

spring:
  application:
    name:  microservice-config-server #指定服务名
  security:
    user: #配置用户的账号信息
      name: zpc
      password: 123456
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://gitee.com/yangfan-ltd/myspconfig.git
          search-paths:
            - myspringcloudconfig		#配置文件目录地址
          username: 18612839069    #码云账号（公有项目不需要设置）
          password: 2017loveyou!@    #码云密码（公有项目不需要设置）
      label: master	#分支名称

###服务注册到eureka注册中心的地址
eureka:
  instance:
    #注册中心地址
    #hostname: 127.0.0.1
    hostname: 39.98.46.129
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${eureka.instance.hostname}
    instance-id: ${spring.application.name}###${server.port} #指定实例id
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 5 # 默认为30秒




management:
  endpoints:
    web:
      exposure:
        include: "*"











