server:
  port: 8087 #服务端口

#myspcloud:
#  item:
#    #url: http://127.0.0.1:8081/item/
#    url: http://39.98.46.129:8081/item/

###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
spring:
  application:
    name: app-order
  security:
    user: #配置用户的账号信息
      name: zpc
      password: 123456

###服务注册到eureka注册中心的地址
eureka:
  instance:
    #注册中心地址
    hostname: 39.98.46.129
    #hostname: 127.0.0.1
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${eureka.instance.hostname}
    instance-id: ${spring.application.name}###${server.port} #指定实例id
  client:
    service-url:
      #defaultZone: http://zpc:123456@39.98.46.129:8100/eureka/,http://zpc:123456@39.98.46.129:9100/eureka/
      #defaultZone: http://zpc:123456@127.0.0.1:8100/eureka,http://zpc:123456@127.0.0.1:9100/eureka
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 5 # 默认为30秒




#app-item:
#  ##自定义的负载均衡策略类
#  ribbon:
#    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule

#开启hystrix断路器
feign:
  hystrix:
    enabled: true