###服务端口号
server:
  port: 9100

###服务名称
spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enable: true #开启基于HTTP basic的认证
    user: #配置用户的账号信息
      name: zpc
      password: 123456

eureka:
  instance: 
    #注册中心地址
    #hostname: 127.0.0.1
    #hostname: 39.98.46.129
    hostname: 39.100.212.7
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${eureka.instance.hostname}
    instance-id: ${spring.application.name}###${server.port} #指定实例id

  ###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    ###是否将自己注册到Eureka服务中,集群的时候为true
    register-with-eureka: true
    fetch-registry: true


  ###测试环境、开发环境可以关闭自我保护机制，保证服务不可用时及时剔除
  server:
    enable-self-preservation: false  # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 2000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    use-read-only-response-cache: false  #自行添加的     读写高速缓存过期策略